# Platform.cmake - Cross-platform environment and prefix configuration

if(WIN32)
    if(EXISTS "C:/msys64/mingw64")
        list(APPEND CMAKE_PREFIX_PATH "C:/msys64/mingw64")
        include_directories("C:/msys64/mingw64/include")
    endif()
    add_compile_definitions(UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
elseif(APPLE)
    if(EXISTS "/opt/homebrew")
        list(APPEND CMAKE_PREFIX_PATH "/opt/homebrew")
        include_directories("/opt/homebrew/include")
        link_directories("/opt/homebrew/lib")
    elseif(EXISTS "/usr/local")
        list(APPEND CMAKE_PREFIX_PATH "/usr/local")
        include_directories("/usr/local/include")
        link_directories("/usr/local/lib")
    endif()
endif()
